name: Dassana Python Action Unit Tests
on:
  pull_request:
    paths:
      - "content/actions/**"
      - "content/pkg/deps/python/**"
    branches:
      - main
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  test-python-layer-common:
    permissions:
      contents: read
    runs-on: ubuntu-18.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v2.0.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
      - uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: 3.8.11
      - name: Cache Python dependencies
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2.1.7
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('content/pkg/deps/python/requirements.txt') }}-${{ hashFiles('content/pkg/deps/python/requirements_dev.txt') }}
      - name: Install dev dependencies
        run: pip install -r requirements_dev.txt
        working-directory: content/pkg/deps/python
      - name: Install Dassana Action (i.e Lambda) specific dependencies
        run: find . -name "requirements.txt" | xargs -I {} pip install -r {}
        working-directory: content/actions
      - name: Run tests for common Python
        run: |
          python -m pytest --hypothesis-show-statistics
        working-directory: content/pkg/deps/python
      - name: Run tests for Dassana Actions in Python
        run: |
          PYTHONPATH=../pkg/deps/python WORKFLOW_DIR=../workflows coverage run -m pytest --hypothesis-show-statistics
        working-directory: content/actions
      - name: Pytest coverage
        run: |
          coverage report
        working-directory: content/actions
