name: Dassana Java Unit Tests
on:
  pull_request:
    paths:
      - "engine/**"
      - "content/**"
    branches:
      - main
jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: |
          cd engine
          mvn --no-transfer-progress --batch-mode test
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
