name: Dassana Linter
on:
  pull_request:
    paths:
      - "content/**"
    branches:
      - main
jobs:
  validate-content-dir-and-file-structure:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # v2.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2.5.1
        with:
          node-version: "14"
      - run: npm install -g @ls-lint/ls-lint
        working-directory: .dassana-internal-devops
      - run: ls-lint
        working-directory: .dassana-internal-devops
  validate-actions-deployment:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # v2.3.1
      - name: Set up Python
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install -r content/pkg/deps/python/requirements.txt --upgrade pip
      - name: Validate workflow steps
        run: |
          python .dassana-internal-devops/scripts/validate-actions-deployment.py
  validate-workflow-steps:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # v2.3.1
      - name: Set up Python
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: 3.7.11
      - name: Install dependencies
        run: |
          python -m pip install -r content/pkg/deps/python/requirements.txt --upgrade pip
      - name: Validate workflow steps
        run: |
          python .dassana-internal-devops/scripts/validate-workflow-steps.py

  validate-id-patterns:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # v2.3.1
      - name: Set up Python
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: 3.7.11
      - name: Install dependencies
        run: |
          python -m pip install -r content/pkg/deps/python/requirements.txt --upgrade pip
      - name: Validate id pattern
        run: |
          python .dassana-internal-devops/scripts/validate-id-patterns.py
