name: Dassana Linter
on:
  pull_request:
    paths:
      - "content/**"
    branches:
      - main
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  validate-content-dir-and-file-structure:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install -g @ls-lint/ls-lint
        working-directory: .dassana-internal-devops
      - run: ls-lint
        working-directory: .dassana-internal-devops
  validate-actions-deployment:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install -r content/pkg/deps/python/requirements.txt --upgrade pip
      - name: Validate workflow steps
        run: |
          python .dassana-internal-devops/scripts/validate-actions-deployment.py
  validate-workflow-steps:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.11
      - name: Install dependencies
        run: |
          python -m pip install -r content/pkg/deps/python/requirements.txt --upgrade pip
      - name: Validate workflow steps
        run: |
          python .dassana-internal-devops/scripts/validate-workflow-steps.py

  validate-id-patterns:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.11
      - name: Install dependencies
        run: |
          python -m pip install -r content/pkg/deps/python/requirements.txt --upgrade pip
      - name: Validate id pattern
        run: |
          python .dassana-internal-devops/scripts/validate-id-patterns.py
