name: Publish Unit Test Coverage
on:
  workflow_dispatch

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # rc
        with: 
          egress-policy: audit
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
      - name: Set up JDK 11
        uses: actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf # v2.5.0
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: |
          cd engine
          mvn --no-transfer-progress --batch-mode test jacoco:report coveralls:report
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
