name: Publish Publicly Facing Content
on:
  push:
    branches:
      - main
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build-and-publish-public-actions-and-policies-dev:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v2.0.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # v2.3.1
        with:
          persist-credentials: false
      - name: Install jq
        run: |
          sudo apt-get update && sudo apt-get install jq -y
      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Parse and dump content into bucket
        run: |
          bash .dassana-internal-devops/scripts/actions.sh | jq '.' -s > .dassana-internal-devops/public/actions.json
          bash .dassana-internal-devops/scripts/policies.sh | jq '.' -s > .dassana-internal-devops/public/policies.json
          aws s3 sync .dassana-internal-devops/public s3://${{ secrets.SAM_ARTIFACTS_BUCKET }}/dev/
