name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  check_pr_labels:
    permissions:
      contents: none
    name: Verify that the PR has the appropriate label(s)
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Check for issue type label
        uses: mheap/github-action-required-labels@d2892166405e47deea29d2052ab4cca1382df41e # v1
        with:
          mode: minimum
          count: 1
          labels: "bug, feature, enhancement, chore, documentation"
